import mongoose from 'mongoose';

const type_of_diseases = [
    'Infectious Diseases',
    'Bacterial Infections',
    'Viral Infections',
    'Fungal Infections',
    'Parasitic Diseases',
    'Cardiovascular Diseases',
    'Coronary Artery Disease',
    'Heart Failure',
    'Arrhythmias',
    'Hypertension',
    'Respiratory Diseases',
    'Asthma',
    'Chronic Obstructive Pulmonary Disease (COPD)',
    'Pneumonia',
    'Pulmonary Fibrosis',
    'Neurological Disorders',
    'Alzheimer\'s Disease',
    'Parkinson\'s Disease',
    'Epilepsy',
    'Multiple Sclerosis',
    'Gastrointestinal Diseases',
    'Gastroesophageal Reflux Disease (GERD)',
    'Inflammatory Bowel Disease (IBD)',
    'Irritable Bowel Syndrome (IBS)',
    'Cirrhosis',
    'Endocrine Disorders',
    'Diabetes Mellitus',
    'Thyroid Disorders',
    'Osteoporosis',
    'Metabolic Syndrome',
    'Musculoskeletal Disorders',
    'Arthritis',
    'Osteoarthritis',
    'Rheumatoid Arthritis',
    'Osteoporosis',
    'Mental Health Disorders',
    'Depression',
    'Anxiety Disorders',
    'Bipolar Disorder',
    'Schizophrenia',
    'Autoimmune Diseases',
    'Rheumatoid Arthritis',
    'Lupus',
    'Type 1 Diabetes',
    'Multiple Sclerosis',
    'Genetic Disorders',
    'Cystic Fibrosis',
    'Down Syndrome',
    'Huntington\'s Disease',
    'Sickle Cell Anemia',
    'Cancer',
    'Breast Cancer',
    'Lung Cancer',
    'Prostate Cancer',
    'Leukemia',
    'Skin Conditions',
    'Eczema',
    'Psoriasis',
    'Acne',
    'Melanoma',
    'Blood Disorders',
    'Anemia',
    'Hemophilia',
    'Leukemia',
    'Lymphoma'
  ];

  const disease_mames = [
    // Infectious Diseases
    'Influenza (Flu)',
    'COVID-19',
    'Tuberculosis',
    'Malaria',
    'HIV/AIDS',
    'Hepatitis B',
    'Hepatitis C',
    'Dengue Fever',
    'Lyme Disease',
    'Measles',
    
    // Cardiovascular Diseases
    'Coronary Artery Disease',
    'Myocardial Infarction (Heart Attack)',
    'Congestive Heart Failure',
    'Atrial Fibrillation',
    'Hypertension (High Blood Pressure)',
    'Atherosclerosis',
    'Peripheral Artery Disease',
    'Stroke',
    'Deep Vein Thrombosis',
    
    // Respiratory Diseases
    'Asthma',
    'Chronic Obstructive Pulmonary Disease (COPD)',
    'Pneumonia',
    'Lung Cancer',
    'Pulmonary Embolism',
    'Cystic Fibrosis',
    'Pulmonary Hypertension',
    'Tuberculosis',
    
    // Neurological Disorders
    'Alzheimer\'s Disease',
    'Parkinson\'s Disease',
    'Epilepsy',
    'Multiple Sclerosis',
    'Migraine',
    'Amyotrophic Lateral Sclerosis (ALS)',
    'Huntington\'s Disease',
    'Cerebral Palsy',
    
    // Gastrointestinal Diseases
    'Gastroesophageal Reflux Disease (GERD)',
    'Peptic Ulcer Disease',
    'Crohn\'s Disease',
    'Ulcerative Colitis',
    'Irritable Bowel Syndrome (IBS)',
    'Cirrhosis',
    'Pancreatitis',
    'Gallstones',
    
    // Endocrine Disorders
    'Type 1 Diabetes',
    'Type 2 Diabetes',
    'Hypothyroidism',
    'Hyperthyroidism',
    'Cushing\'s Syndrome',
    'Addison\'s Disease',
    'Polycystic Ovary Syndrome (PCOS)',
    
    // Cancer Types
    'Breast Cancer',
    'Prostate Cancer',
    'Colorectal Cancer',
    'Leukemia',
    'Lymphoma',
    'Melanoma',
    'Ovarian Cancer',
    'Pancreatic Cancer',
    
    // Autoimmune Diseases
    'Rheumatoid Arthritis',
    'Systemic Lupus Erythematosus',
    'Multiple Sclerosis',
    'Type 1 Diabetes',
    'Psoriasis',
    'Inflammatory Bowel Disease',
    'Celiac Disease',
    
    // Mental Health Disorders
    'Major Depressive Disorder',
    'Generalized Anxiety Disorder',
    'Bipolar Disorder',
    'Schizophrenia',
    'Obsessive-Compulsive Disorder (OCD)',
    'Post-Traumatic Stress Disorder (PTSD)',
    'Autism Spectrum Disorder',
    
    // Rare Diseases
    'Ehlers-Danlos Syndrome',
    'Marfan Syndrome',
    'Tay-Sachs Disease',
    'Gaucher\'s Disease',
    'Fabry Disease',
    'Prader-Willi Syndrome',

    'Unknown'
  ];

const diseaseSchema = new mongoose.Schema({
    name: {
        type: String,
        required: true,
        unique: true,
        trim: true,
        enum: disease_mames,
        minlength: 1,
        maxlength: 100,
        default: 'Unknown',
    },
    type_of_disease: {
        type: String,
        required: true,
        enum: type_of_diseases,
        default: 'Unknown',
    },
    description: {
        type: String,
        required: true,
        trim: true,
        minlength: 1,
        maxlength: 1000,
        default: 'None',
    },
    symptoms: {
        type: [String],
        required: true,
        default: [],
    },
    causes: {
        type: [String],
        required: true,
        default: [],
    },
    prevention: {
        type: [String],
        required: true,
        default: [],
    },
    contagius: {
        type: Boolean,
        required: true,
        default: false,
    },
    hospital_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Hospital',
        required: true,
    },
    drug_ids: {
        type: [mongoose.Schema.Types.ObjectId],
        ref: 'Drug',
        required: true,
    },
    createdAt: {
        type: Date,
        default: Date.now,
    },
});

const Disease = mongoose.model('Disease', diseaseSchema);
export default Disease;
